
<option value=1>Tijuaçu</option>
<option value=2>Mata Machado</option>
<option value=3>Biguá</option>
<option value=4>Maracaí</option>
<option value=5>Butui</option>
<option value=6>Minha Deusa</option>
<option value=7>Agricola</option>
<option value=8>Valeriano</option>
<option value=9>Furnas</option>
<option value=10>Soberbo</option>
<option value=11>Bombeiro</option>
<option value=12>Gavea Pequena(Alto)</option>
<option value=13>Praça do Alto</option>
<option value=14>Açude</option>
<option value=15>Casa do Prefeito</option>
<option value=16>Taquara do Alto</option>
<option value=17>Vista Chinesa</option>
<option value=18>Morro do Banco</option>
<option value=19>Itanhangá</option>
<option value=20>Tijuquinha</option>
<option value=21>Usina</option>
<option value=22>Estrada Velha</option>